[project]
name = "class-project"
version = "0.1.0"
description = "Class project for writing tasks"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai-agents>=0.0.16",
    "python-dotenv>=1.0.0",
    "streamlit>=1.31.0",
]